// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdnGsJI2a99arfmrsvL6BF0BiDZnanAZQ',
    appId: '1:854773143957:web:b7606f71407b9271033e9c',
    messagingSenderId: '854773143957',
    projectId: 'loyalty-app-a13a0',
    authDomain: 'loyalty-app-a13a0.firebaseapp.com',
    storageBucket: 'loyalty-app-a13a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8EwkYiEvGPA0cp-fXO9Sg6ajw4Tfs3bg',
    appId: '1:854773143957:android:775f87873738cede033e9c',
    messagingSenderId: '854773143957',
    projectId: 'loyalty-app-a13a0',
    storageBucket: 'loyalty-app-a13a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnbLRhIc4NeLlZyONh5uztEbrrWCsehvE',
    appId: '1:854773143957:ios:238c8411c5a7c7ef033e9c',
    messagingSenderId: '854773143957',
    projectId: 'loyalty-app-a13a0',
    storageBucket: 'loyalty-app-a13a0.appspot.com',
    iosClientId: '854773143957-2v5basboobll6k0h7joql30qfp9n0tkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.loyaltyAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnbLRhIc4NeLlZyONh5uztEbrrWCsehvE',
    appId: '1:854773143957:ios:238c8411c5a7c7ef033e9c',
    messagingSenderId: '854773143957',
    projectId: 'loyalty-app-a13a0',
    storageBucket: 'loyalty-app-a13a0.appspot.com',
    iosClientId: '854773143957-2v5basboobll6k0h7joql30qfp9n0tkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.loyaltyAdmin',
  );
}
